services:
  - type: web
    name: tradeai-companion
    runtime: python3
    plan: starter  # Can be upgraded to standard or pro as needed
    buildCommand: "./build.sh"
    startCommand: "gunicorn main:app --bind 0.0.0.0:$PORT --workers 2 --worker-class uvicorn.workers.UvicornWorker --timeout 120"
    healthCheckPath: "/health"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: TELEGRAM_API_TOKEN
        sync: false  # Set this in Render dashboard
      - key: OPENAI_API_KEY
        sync: false  # Set this in Render dashboard
      - key: ALPACA_API_KEY
        sync: false  # Set this in Render dashboard (optional)
      - key: ALPACA_API_SECRET
        sync: false  # Set this in Render dashboard (optional)
      - key: CHART_IMG_API_KEY
        sync: false  # Set this in Render dashboard (optional)
      - key: REDIS_URL
        fromService:
          type: redis
          name: tradeai-redis
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: tradeai-db
          property: connectionString
      - key: PORT
        value: 8080
      - key: ENVIRONMENT
        value: production
      - key: PYTHONPATH
        value: .
      - key: TZ
        value: UTC
      - key: APSCHEDULER_TIMEZONE
        value: UTC

  - type: redis
    name: tradeai-redis
    plan: starter
    ipAllowList: []

databases:
  - name: tradeai-db
    plan: starter
    databaseName: tradeai_companion
    user: tradeai_user